name: PlateouKillAura
version: 1.0
main: org.idroom.PlateouKillAura
api-version: 1.21
description: A plugin to notify staff about potential KillAura users.
author: YourName
permissions:
  plateoukillaura.notify:
    description: Allows receiving notifications about potential KillAura users.
    default: op