name: PlateouTabCompleter
main: org.idroom.PlateouTabCompleter
version: 1.0
api-version: 1.20
author: YourName
description: Prevents players from using certain commands and tab completion.
commands:
  plugins:
    description: Fake command to override default behavior.
  pl:
    description: Fake command to override default behavior.
